export class PurchaseRequisition {
    public nPRNID: number;
    public dtPRNDate: Date;
    public sPRNApprovalStatus: string;
    public sPRNCreatedBy: string;
    public sPRNProject: string;
    public sPRNRequestInitiatedBy: string;
    public bPRNTaxable: boolean;
    public sPRNPriority: string;
    public sPRNPurchaseOrderNo: string;
    public sTermCode: string;
    public nPRNDueInDays: number;
    public sPRNShipVia: string;
    public sPRNFOB: string;
    public dtPRNDateOrdered: Date;
    public dtPRNDateRequired: Date;
    public sPRNDeliverTo: string;
    public sPRNVendorName: string;
    public sPRNVendorContact: string;
    public sPRNVendorPhone: string;
    public sPRNVendorFax: string;
    public sPRNVendorAddress: string;
    public sPRNNotes: string;
    public bPRNManagerApprovalNeeded: boolean;
    public bPRNPresidentApprovalNeeded: boolean;
    public dtPRNFinalApprovalDate: Date;
    public nExtendedTotal: string;
    public nExtendedTotalWithTaxes: string;
    public nPRNApproverCode: string;
    public sPRNApproversUserName: string;
    public sApprovelComment: string;
    public sUpdatedBy: string;
    public dtUpdatedOn: Date;

    constructor() {
        this.nPRNID = 0;
        this.dtPRNDate = new Date();
        this.sPRNApprovalStatus = '';
        this.sPRNCreatedBy='';
        this.sPRNProject='';
        this.sPRNRequestInitiatedBy='';
        this.bPRNTaxable=false;
        this.sPRNPriority='';
        this.sPRNPurchaseOrderNo='';
        this.sTermCode ='';
        this.nPRNDueInDays = 0;
        this.sPRNShipVia ='';
        this.sPRNFOB='';
        this.dtPRNDateOrdered=new Date;
        this.dtPRNDateRequired=new Date;
        this.sPRNDeliverTo='';
        this.sPRNVendorName='';
        this.sPRNVendorContact='';
        this.sPRNVendorPhone='';
        this.sPRNVendorFax='';
        this.sPRNVendorAddress='';
        this.sPRNNotes='';
        this.bPRNManagerApprovalNeeded=false;
        this.bPRNPresidentApprovalNeeded=false;
        this.dtPRNFinalApprovalDate=new Date();
        this.nExtendedTotal='';
        this.nExtendedTotalWithTaxes='';
        this.nPRNApproverCode='';
        this.sPRNApproversUserName='';
        this.sApprovelComment='';
        this.sUpdatedBy='';
        this.dtUpdatedOn=new Date(); 
    }
}